### ISSUE TITLE
UI Bug tracking list for release-candidate-0.9.0

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#1857]
Although the [release branch for 0.9.0](https://github.com/bisq-network/bisq/tree/release-candidate-0.9.0) is still work in progress I start this issue to collect all open todos. Feel free to leave comments on UI glitches so we don't miss anything.

Views that are not done yet:
- Trade process

## Views to adapt
- [x] Take Offer
- [x] Edit Offer
- [x] Create Offer
- [x] Trade Process
- [x] Trade Details Window
- [x] Contract Window 
- [x] Dispute Summary Window
- [x] Arbitration

## Open Tasks
- [ ] Check if rendering intensive views can be delayed not to conflict with ripple effect in e.g. tabs
- [x] Style interval buttons (TradeStatistics,...)
- [x] Replace all BusyAnimations with JFXSpinner
- [x] Improve styling of small notification popups
- [x] click on avatar opens small popup with user info
- [x] tor network settings popup (settings/network)
- [x] seed word restore at startup or in account view
- [x] testing all with password
- [x] testing bsq/btc trade fee with DaoEnabled= false in DevEnv -> BSQ must be hidden
- [x] DAO screens still have old style of left navigation
- [x] The market price display is too small for some altcoins with 8 digits. also balances can be truncates. availabel balance can have up to 8 digits after comma, others only 4.
- [x] Create offer buttons in buy/sell screens should be above table
- [x] fix Ripple position for RadioButtons
- [x] Adapt date picker
- [x] Adapt chart style in Trades view
- [x] Extend focus line in create offer view until the end of the box also increase length of fields to fit error text
-  [x] Reduce line space in payment methods display

## Optional
- [x] Focus colors of buttons should always be brighter/darker not lighter (e.g. buy/sell colors)
- [ ] Improve Spinner performance
- [ ] Remove code duplication between CreateOffer and TakeOffer views
- [ ] Use ButtonBar for all buttons to have consistent positioning
- [ ] Add ripple effect for main navigation
- [ ] Clean up css colors
- [ ] Clean up css classes
- [ ] btc node change triggers popups
- [ ] Improve design of notification popups (x close icon instead of cancel/close button,...)
- [ ] Define new colors for the message bubbles during dispute

**Comment by iljah** [comment]
Disconnecting from (all?/only) btc node makes UI get stuck for several minutes: https://github.com/bisq-network/bisq/issues/1823

**Comment by ManfredKarrer** [comment]
A few small screens we must not forget:
- click on avatar opens small popup with user info
- tor network settings popup (settings/network)
- btc node change triggers popups
- seed word restore at startup or in account view
- testing all with password
- testing bsq/btc trade fee with DaoEnabled= false in DevEnv -> BSQ must be hidden
- interval button bar in market/trades is still old style
- DAO screens still have old style of left navigation

Other remarks:
- The market price display is too small for some altcoins with 8 digits. also balances can be truncates. availabel balance can have up to 8 digits after comma, others only 4. 
- Create offer buttons in buy/sell screens should be above table

**Comment by ripcurlx** [comment]
@ManfredKarrer Thanks - I've updated the open tasks list.

**Comment by ManfredKarrer** [comment]
Small issues whith bracket and colon in titles (IBAN...). See
<img width="544" alt="screen shot 2018-11-07 at 12 29 36" src="https://user-images.githubusercontent.com/1449498/48151241-c26da880-e28e-11e8-8fa9-ca4d49542a7c.png">

**Comment by ripcurlx** [comment]
Ah - I only fixed this in CashDeposit and missed it in the BankForm. Will fix it tomorrow.

**Comment by ripcurlx** [comment]
@ManfredKarrer What do you mean with 
> btc node change triggers popups

**Comment by ManfredKarrer** [comment]
> btc node change triggers popups

If you change from provided btc nodes to public nodes in settings/network. There are some popups there...

**Comment by ManfredKarrer** [comment]
Small thing to not forget: The logo at splash screen is too small (prob 50% of the intended size)

**Comment by ManfredKarrer** [comment]
We need also another tor icon, it hurts the eye as it is now ;-). maybe we just make an abstract green one. their purple will never fit (nowhere ;-)).

**Comment by ripcurlx** [comment]
@ManfredKarrer These are the btc node popups. Do we really need a custom styling for them?

<img width="1284" alt="bildschirmfoto 2018-11-13 um 13 30 45" src="https://user-images.githubusercontent.com/170962/48413560-5d132f00-e748-11e8-8abe-3a811247362b.png">
<img width="1284" alt="bildschirmfoto 2018-11-13 um 13 30 35" src="https://user-images.githubusercontent.com/170962/48413562-5edcf280-e748-11e8-8ff4-08e475f90ff2.png">

**Comment by ManfredKarrer** [comment]
I think it would be better to have the fields in the bottom be full width and qr code right aligned
<img width="1192" alt="screen shot 2018-11-19 at 14 05 30" src="https://user-images.githubusercontent.com/1449498/48728894-48311280-ec04-11e8-89fe-747167a53a07.png">

**Comment by ManfredKarrer** [comment]
Similar on send funds screen

**Comment by ManfredKarrer** [comment]
Fields in row are not centered.
<img width="1200" alt="screen shot 2018-11-19 at 14 08 06" src="https://user-images.githubusercontent.com/1449498/48729024-934b2580-ec04-11e8-9372-5be98373750d.png">

**Comment by ManfredKarrer** [comment]
At preferences screen the buttons have no hand cursor

**Comment by ManfredKarrer** [comment]
Textarea has green line as well. I think here it better without line. 
<img width="1187" alt="screen shot 2018-11-19 at 14 10 50" src="https://user-images.githubusercontent.com/1449498/48729166-f2109f00-ec04-11e8-86a0-77d52b1568e4.png">

**Comment by ManfredKarrer** [comment]
That popup exceeds height of app window. Should be more condensed.
Seperator lines have too high distance. Button no hand cursor and Textarea comes with line as well.

Default (green) button should be not delete tor files. Not sure whats now and whats best...

<img width="1014" alt="screen shot 2018-11-19 at 14 12 33" src="https://user-images.githubusercontent.com/1449498/48729265-34d27700-ec05-11e8-844c-1e3fbe40e1f3.png">

**Comment by ManfredKarrer** [comment]
I think account should also fill whole width.
Distance between comboboxes is smaller as between text fields. Better to have it smaller to not lose so much space.
<img width="1208" alt="screen shot 2018-11-19 at 14 16 12" src="https://user-images.githubusercontent.com/1449498/48733922-f0010d00-ec11-11e8-80d7-52c164e77cf9.png">

**Comment by ManfredKarrer** [comment]
Font in some tables are monospace in otheres normal font. Here they are mixed.
<img width="1187" alt="screen shot 2018-11-19 at 14 48 17" src="https://user-images.githubusercontent.com/1449498/48731098-35b9d780-ec0a-11e8-9d0c-acda074e5180.png">

**Comment by ManfredKarrer** [comment]
For me it looks a bit strange that the label text left is grey and not black.
<img width="1150" alt="screen shot 2018-11-19 at 14 49 53" src="https://user-images.githubusercontent.com/1449498/48731158-67cb3980-ec0a-11e8-9857-afa9aad83cf5.png">

**Comment by ManfredKarrer** [comment]
Not sure if dottel line is good here. Maybe just no line?
<img width="1092" alt="screen shot 2018-11-19 at 14 50 49" src="https://user-images.githubusercontent.com/1449498/48731206-88938f00-ec0a-11e8-9698-dd4ba439c555.png">

**Comment by ManfredKarrer** [comment]
I think distance between header and first is to small but  the sistance between the text fields is perfect IMO. We should use that at other non input fields as well.
<img width="396" alt="screen shot 2018-11-19 at 14 58 08" src="https://user-images.githubusercontent.com/1449498/48731668-909ffe80-ec0b-11e8-9f43-0b351e5bfb98.png">

**Comment by ManfredKarrer** [comment]
Not sure if green as color for links is so good. It gets quite fulled up in some screens with green, losing the CI color weight IMO.

<img width="1152" alt="screen shot 2018-11-19 at 15 01 00" src="https://user-images.githubusercontent.com/1449498/48731817-f55b5900-ec0b-11e8-9b33-bc71634b1939.png">

**Comment by ripcurlx** [comment]
Yes, I'm also not so sure if we should switch the blue link color with the new green everywhere.

**Comment by ManfredKarrer** [comment]
Yes, lets maybe ask @pedromvpg what he suggests. Looks not with screens filled with real data different than with blank screens...

**Comment by ManfredKarrer** [comment]
I assume the blue here is not intended...
<img width="383" alt="screen shot 2018-11-19 at 15 03 36" src="https://user-images.githubusercontent.com/1449498/48732003-71ee3780-ec0c-11e8-9f0d-5b6ae749f491.png">

**Comment by ripcurlx** [comment]
Atm it is, as it is the volume. Not sure if using green would be confusing regarding loss/win, especially if you have the other chart displayed above it.

**Comment by ManfredKarrer** [comment]
With cmd+j the wallet info popup gets opened. It has column issues atm.

**Comment by ManfredKarrer** [comment]
When sending a dispute msg and the peer is offline there is a spinner short time and that is not centered with % text in there

**Comment by ripcurlx** [comment]
> I assume the blue here is not intended...
> <img alt="screen shot 2018-11-19 at 15 03 36" width="383" src="https://user-images.githubusercontent.com/1449498/48732003-71ee3780-ec0c-11e8-9f0d-5b6ae749f491.png">
Not sure what color would be best for volume bars instead.
<img width="1312" alt="bildschirmfoto 2018-11-19 um 21 08 26" src="https://user-images.githubusercontent.com/170962/48732207-46387500-ec3f-11e8-8c96-8aaa0d3ee961.png">

**Comment by ManfredKarrer** [comment]
Maybe green is better here? But not sure either...

**Comment by ManfredKarrer** [comment]
In disputes its system msg green and then blue/grey. maybe better green/grey and diff. color for system msg?

**Comment by ripcurlx** [comment]
I could use the blue for the system message 😉

**Comment by ManfredKarrer** [comment]
Some colons still
<img width="330" alt="screen shot 2018-11-19 at 15 11 44" src="https://user-images.githubusercontent.com/1449498/48732358-7535f300-ec0d-11e8-837f-6b0613d0360e.png">

**Comment by ManfredKarrer** [comment]
Avatar icon tags (circle with num trades, info msg) are still blue.

**Comment by ManfredKarrer** [comment]
Some tables have lines between rows others not (market vs trades).

**Comment by ripcurlx** [comment]
> Some tables have lines between rows others not (market vs trades).

Yes, I took it from the design templates right now, which have it different. Maybe we should make them more consistent.

**Comment by ManfredKarrer** [comment]
Currency list exceed my screen. Prob. max entries need to be lower as rows are higher now.

**Comment by ManfredKarrer** [comment]
Sepa account has last 2 entries too much space when viewing account (prob not when creating it)

**Comment by ManfredKarrer** [comment]
Green border prob not intended
<img width="906" alt="screen shot 2018-11-19 at 15 22 53" src="https://user-images.githubusercontent.com/1449498/48732905-035ea900-ec0f-11e8-8f95-0bf1dc7bc4d0.png">

**Comment by ripcurlx** [comment]
> Sepa account has last 2 entries too much space

I gave the limitation and salt extra space and only compressed the payment account specific fields. But I guess it didn't help readability. I'll decrease the line space there as well.

**Comment by ripcurlx** [comment]
> Textarea has green line as well. I think here it better without line.
> <img alt="screen shot 2018-11-19 at 14 10 50" width="1187" src="https://user-images.githubusercontent.com/1449498/48729166-f2109f00-ec04-11e8-86a0-77d52b1568e4.png">

I fixed the positioning of the textarea focus line, but I think it should stay to be consistent with other input fields.

**Comment by ripcurlx** [comment]
> Avatar icon tags (circle with num trades, info msg) are still blue.

@pedromvpg I think we would need an alternative color or keep the blue.
Having both circles green makes it harder to grasp.

![bildschirmfoto 2018-11-21 um 11 58 58](https://user-images.githubusercontent.com/170962/48837166-dc29e800-ed84-11e8-94e0-8b6c9882d93a.png)

**Comment by joachimneumann** [comment]
Hi, I have installed Bisq-0.9.0-2018-11-21.dmg from dropbox and tried set up notification by pairing with my iPhone.
1. The pairing worked, but took unusually long (about 40 seconds). I'll try again later.
2. Adding offer alerts did not show my SEPA account in the drop down list, see screenshot.
<img width="527" alt="screenshot 2018-11-22 at 11 32 26" src="https://user-images.githubusercontent.com/5642225/48882012-ced73100-ee4a-11e8-8886-1fee6917eab7.png">

I love the new design, it looks more modern and professional.

**Comment by ripcurlx** [comment]
@joachimneumann I think the content for this combobox wasn't bound to the "live" data. It is populated when you open it for the first time after an app start. I'll fix it.

**Comment by ripcurlx** [comment]
@joachimneumann Fixed it - the pairing worked for me instantly.

**Comment by ManfredKarrer** [comment]
The notification popups are right aligned but not top aligned (5-10 px distance). I think would be better to have both without space or with the same space.

**Comment by ManfredKarrer** [comment]
Buttons are sometimes not in the full color. I think its an artefact fromt he animations that the color/alpha animation does not continue to the end. It happens for instance at create offer at the confirm popup at the end. when canceling that the main screen button is also not full color.
<img width="730" alt="screen shot 2018-11-23 at 21 30 08" src="https://user-images.githubusercontent.com/1449498/48959633-fd4a2e80-ef66-11e8-99e1-4ac53205166b.png">
<img width="862" alt="screen shot 2018-11-23 at 21 30 13" src="https://user-images.githubusercontent.com/1449498/48959634-fd4a2e80-ef66-11e8-95b8-dc07c2c6169b.png">


Seems if you click somewhere the animation finishes. Maybe some focus issue?

**Comment by ManfredKarrer** [comment]
Spinner use a lot of CPU. When spinner is animated CPU is about 20% otherwise its 1-3 %.
Thats the old problem with the JavaFX progress indicator. I optimized in the old version those classes to use less CPU (is about 10%). No need to fix it for that release but we should either try to find an alternative or fix the CPU issue in follow up releases. Shame on Oracle that they are unable to build such a simple animation with performacne in mind.
<img width="858" alt="screen shot 2018-11-23 at 21 32 47" src="https://user-images.githubusercontent.com/1449498/48959687-5914b780-ef67-11e8-9df3-c293e11ac479.png">

**Comment by ManfredKarrer** [comment]
At create offer there is short time something visible when next button is clicked. I cannot see it what it is as it is too short, but you can see that the layout of the funding screen gets re-layouted after 200 ms or so...

**Comment by ManfredKarrer** [comment]
Scrolling through offers shows some fields blank. Prob. a incorrect cell update.
<img width="1199" alt="screen shot 2018-11-25 at 03 30 55" src="https://user-images.githubusercontent.com/1449498/48974781-9873fe80-f062-11e8-9eb0-854051fa367b.png">

**Comment by ripcurlx** [comment]
https://github.com/bisq-network/bisq/pull/1973 addresses all issues (except the render bug)

**Comment by ManfredKarrer** [comment]
Most popups have the info style. They come now with the i icon which might be confusing as a user would expect a rollover or the like. Many such popups like password input does not even have any text for info... I would suggest to not show the i icon.

<img width="857" alt="screen shot 2018-11-26 at 22 50 30" src="https://user-images.githubusercontent.com/1449498/49044341-c033a580-f1cd-11e8-8458-9295168549bc.png">

**Comment by ManfredKarrer** [comment]
Red icons are a bit too low:

<img width="258" alt="screen shot 2018-11-26 at 23 13 33" src="https://user-images.githubusercontent.com/1449498/49045321-f32b6880-f1d0-11e8-9449-cb457a9697b5.png">

**Comment by ManfredKarrer** [comment]
When you are in the fund screen in create offer and switch tabs and come back the focus is set to amount field. Should be no focus set if in funding screen.

<img width="367" alt="screen shot 2018-11-26 at 23 20 27" src="https://user-images.githubusercontent.com/1449498/49045644-e22f2700-f1d1-11e8-8487-2effe4d1a3a3.png">

**Comment by ManfredKarrer** [comment]
At edit offer the spinner is animated but not clear what it means. As its a CPU killer maybe best to remove it.

<img width="367" alt="screen shot 2018-11-26 at 23 23 19" src="https://user-images.githubusercontent.com/1449498/49045810-6386b980-f1d2-11e8-91bd-5979b9d7c933.png">

**Comment by ManfredKarrer** [comment]
Confirmation icon in fund screen is too big.

<img width="447" alt="screen shot 2018-11-26 at 23 25 11" src="https://user-images.githubusercontent.com/1449498/49045851-8add8680-f1d2-11e8-857c-5e037aef12bc.png">

**Comment by ManfredKarrer** [comment]
Dispute detail window labels are too short and headline need more space.
<img width="166" alt="screen shot 2018-11-26 at 23 29 11" src="https://user-images.githubusercontent.com/1449498/49046045-24a53380-f1d3-11e8-92a9-285eddf9b209.png">

**Comment by ManfredKarrer** [comment]
Emergency window title has too much space:
<img width="681" alt="screen shot 2018-11-26 at 23 30 54" src="https://user-images.githubusercontent.com/1449498/49046127-6209c100-f1d3-11e8-9b8c-d66fef95b918.png">

**Comment by ripcurlx** [comment]
> When you are in the fund screen in create offer and switch tabs and come back the focus is set to amount field. Should be no focus set if in funding screen.
> 
> <img alt="screen shot 2018-11-26 at 23 20 27" width="367" src="https://user-images.githubusercontent.com/1449498/49045644-e22f2700-f1d1-11e8-8487-2effe4d1a3a3.png">

That's kind of weird. I'm not even able to select/focus this field as it is set to `MouseTransparent=true` and `FocusTraversable=false`. Can you reproduce this every time?

**Comment by ripcurlx** [comment]
> At edit offer the spinner is animated but not clear what it means. As its a CPU killer maybe best to remove it.
> 
> <img alt="screen shot 2018-11-26 at 23 23 19" width="367" src="https://user-images.githubusercontent.com/1449498/49045810-6386b980-f1d2-11e8-91bd-5979b9d7c933.png">

There was a bug that the progress indicator it wasn't stopped after your first edit. So it showed up on all edits afterwards already spinning.

**Comment by ripcurlx** [comment]
> Dispute detail window labels are too short and headline need more space.
> <img alt="screen shot 2018-11-26 at 23 29 11" width="166" src="https://user-images.githubusercontent.com/1449498/49046045-24a53380-f1d3-11e8-92a9-285eddf9b209.png">

Did you resize the window before you opened the dialoge? I don't see this issue, besides the needed padding for the title.
![bildschirmfoto 2018-11-27 um 11 36 17](https://user-images.githubusercontent.com/170962/49076206-c0b55600-f238-11e8-843b-cb22393956e5.png)

**Comment by ManfredKarrer** [comment]
@ripcurlx do u want to keep that open?

**Comment by ripcurlx** [comment]
I'll split the remaining tasks into separate issues and close this one afterwards.

**Comment by ripcurlx** [comment]
Closing as complete. All open tasks have been moved into separate issues.
