### ISSUE TITLE
Trading partners can meet via IRC to simulate national currency payment

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#199]
## Motivation

Because everything in early Bitsquare milestones happens over the bitcoin testnet, no value is exchanged, and therefore real payments via bank transfer do not make sense. This story simplifies the process process by allowing users to meet via IRC to simulate the fiat half of the trade.
## Example
- Bob and Alice each enter their Freenode IRC nicknames during account creation in the Bitsquare UI
- Bob places an offer to buy 1 bitcoin
- Alice takes the offer, agreeing to sell Bob 1 bitcoin
- Bob is instructed via his Bitsquare UI to meet Alice in #bitsquare-trading
- Alice is instructed via her Bitsquare UI to meet Bob in #bitsquare-trading 
- Bob and Alice find each other by their nicknames in #bitsquare-trading
- Bob writes a payment message to Alice "Payment initiated" in the Bitsquare UI
- Alice receives the payment message and responds by clicking "Payment received" in the Bitsquare UI
- The trade process completes normally, and Alice withdraws her newly-"purchased" bitcoin
## Tasks
- [x] Register #bitsquare-trading (#185)
- [x] Provide in-app link to #bitsquare-trading IRC webchat (#208)
- [x] Provide IRC-based payments method and make it the default (#209)
- [x] Disable bank-based payments method (#210)
- [x] Update account registration logic to record hashed IRC nickname (#211)

**Comment by ManfredKarrer** [comment]
Update: Removed from the current version as it was too confusing for users.
