### ISSUE TITLE
Users can download platform native Bitsquare executables

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#207]
## Motivation

Users need to be able to download v0.1 installer binaries from the http://bitsquare.io website.
## Steps
- [x] Add build support for generating native installers (#243)
- [x] Fix the missing .dll problem on Windows (#297)
- [x] Add a downloads page to the bitsquare.io site (bitsquare/site#24)

**Comment by ManfredKarrer** [comment]
@cbeams could you upload the binaries under releases? so users can start trying it out before the testing session?

**Comment by cbeams** [comment]
> @cbeams could you upload the binaries under releases? so users can start trying it out before the testing session?

Yes, doing that now...

**Comment by cbeams** [comment]
Done: https://github.com/bitsquare/bitsquare/releases/tag/v0.1.0-SNAPSHOT.1

**Comment by ManfredKarrer** [comment]
Thannks!

**Comment by cbeams** [comment]
Closing this, marking as done, given that we have everything in place for users to download binaries, including a prominent 'download' link on the bitsquare.io site. The actual release of v0.1 and upload of those specific binaries to GitHub Releases will be handled in a separate issue.

**Comment by ManfredKarrer** [comment]
I tried to run the actual binary on ubuntu but it complained that a newer version is already installed. Extraceting the deb file and run Bitsquare in the opt/Bitsquare dir works.
