### ISSUE TITLE
Hide incomplete functionality

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#212]
## Motivation

There are a number of partially-implemented elements in the Bitsquare UI that do not add value during early milestones. To improve first impressions and help users understand Bitsquare's strengths, disable any functionality that is not critical to the core use cases of placing and taking offers and completing the trade process.
### On the account setup screen
- [x] Disable “Backup wallet seed” panel (#213)
- [x] Disable “Setup password” panel (#214)
- [x] Disable “Trade constraints” in “Setup your preferences” panel (#215)
- [x] Disable all “Payment methods” other than IRC in the “Setup Payments account(s)” panel (#216)
- [x] Rename “Setup your preferences” panel to “Arbitration selection” (#217)
